// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bqjodqzzyicqgyckexji.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxam9kcXp6eWljcWd5Y2tleGppIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDUxMTgsImV4cCI6MjA2ODg4MTExOH0.tY-P9YQBDhDCine6t51g1bkoZ9RsSwLdmXQbtfqh_HA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});